# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install: 
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  # Replace dep1 dep2 ... with your dependencies
  - conda create -n TDE --file conda-requirements.txt 
  - source activate TDE
  # Install remaining dependencies with pip 
  - pip install -r pip-requirements.txt
  - ls /home/travis/build/jukaradayi/tde/tde/substrings/
  - python setup.py build
  - python setup.py install

# command to run tests, e.g. python setup.py test
script: 
 - pytest tests/
