name: "TDE_TEST"
channels:
    - 'defaults'
dependencies:
    - 'numpy'
    - 'openssl'
    - 'pandas=0.20'
    - 'pip'
    - 'cython'
    - 'scipy'
    - 'mock'
    - 'numpydoc'
    - 'pytest'
    - 'pip':
        - 'joblib'
        - 'editdistance'
        - 'intervaltree'
        - 'ipdb'
